httpbakery: Add context to to client methods.
go-macaroon-bakery/macaroon-bakery pull request #118
Opened 2016-11-22 08:04 UTC by mhilton

Add a DoWithContext method and use the context with all HTTP
requests. Also add context to DischargeAll and HandleError methods.

2016-11-22 09:23 UTC, mattyw approved these changes

2016-11-22 12:04 UTC, rogpeppe requested changes
LGTM but I have a concern about the proliferation of Do methods.

2016-11-22 12:04 UTC, rogpeppe commented on httpbakery/client.go
> +// with a *InteractionError cause will be returnedif this interaction
returned if

2016-11-22 12:04 UTC, rogpeppe commented on httpbakery/client.go
> +// relativeURL returns newPath relative to an original URL.
Thanks for moving this.

2016-11-22 12:04 UTC, rogpeppe commented on httpbakery/client_test.go
>  	c.Assert(err, gc.IsNil)
I wonder if we should test whether the context actually gets through to the parts we intend it to.

2016-11-22 12:04 UTC, rogpeppe commented on httpbakery/client.go
> +func (c *Client) DoWithContext(ctx context.Context, req *http.Request) (*http.Response, error) {
I'm not sure about having another Do variant again now we've eliminated DoWithBody.. For example, what about DoWithContextAndCustomError?

How about just adding a context to Do and DoWithCustomError and don't bother to derive the context from the request?
At some point when we can use Go 1.7 we can break the API and take the context argument out and derive it from the request.

For now, I think all our pre-1.7 programs will need to pass in the request explicitly anyway.

2016-12-01 07:18 UTC, mhilton commented on httpbakery/client.go
> +// with a *InteractionError cause will be returnedif this interaction
done

2016-12-01 07:19 UTC, mhilton commented on httpbakery/client.go
> +func (c *Client) DoWithContext(ctx context.Context, req *http.Request) (*http.Response, error) {
As discussed this is the interface we are using with httprequest

2016-12-01 07:19 UTC, mhilton commented on httpbakery/client.go
> +// relativeURL returns newPath relative to an original URL.
you're welcome

2016-12-01 08:18 UTC, rogpeppe approved these changes

2016-12-01 08:18 UTC, merged